version: '3.7'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.1'
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  kibana:
    image: 'docker.elastic.co/kibana/kibana-oss:7.0.1'
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  logstash:
    build: ./Logstash
    volumes:
      - ./Logstash/pipeline/:/usr/share/logstash/pipeline/
    depends_on:
      - elasticsearch
  filebeat:
    build: ./Filebeat
    volumes:
      - ../Logs/:/usr/share/filebeat/hostlogs/
    depends_on: 
      - kibana
      - logstash
      - elasticsearch